// Ländernamen-Mapping (Korrektur der radio-browser.info Namen)
export const COUNTRY_NAMES = {
  'The United States Of America': 'USA',
  'United States of America': 'USA',
  'The Russian Federation': 'Russland',
  'Russian Federation': 'Russland',
  'Germany': 'Deutschland',
  'France': 'Frankreich',
  'Australia': 'Australien',
  'Austria': 'Österreich',
  'Switzerland': 'Schweiz',
  'Netherlands': 'Niederlande',
  'The Netherlands': 'Niederlande',
  'Belgium': 'Belgien',
  'Brazil': 'Brasilien',
  'Spain': 'Spanien',
  'Italy': 'Italien',
  'Japan': 'Japan',
  'China': 'China',
  'India': 'Indien',
  'Canada': 'Kanada',
  'Mexico': 'Mexiko',
  'Poland': 'Polen',
  'Sweden': 'Schweden',
  'Norway': 'Norwegen',
  'Denmark': 'Dänemark',
  'Finland': 'Finnland',
  'Czech Republic': 'Tschechien',
  'Czechia': 'Tschechien',
  'Hungary': 'Ungarn',
  'Romania': 'Rumänien',
  'Turkey': 'Türkei',
  'Greece': 'Griechenland',
  'Portugal': 'Portugal',
  'Argentina': 'Argentinien',
  'Colombia': 'Kolumbien',
  'Chile': 'Chile',
  'Peru': 'Peru',
  'Indonesia': 'Indonesien',
  'South Korea': 'Südkorea',
  'Thailand': 'Thailand',
  'Ukraine': 'Ukraine',
  'Ireland': 'Irland',
  'New Zealand': 'Neuseeland',
  'South Africa': 'Südafrika',
  'Croatia': 'Kroatien',
  'Serbia': 'Serbien',
  'Bulgaria': 'Bulgarien',
  'Slovakia': 'Slowakei',
  'Slovenia': 'Slowenien',
  'Lithuania': 'Litauen',
  'Latvia': 'Lettland',
  'Estonia': 'Estland',
  'Luxembourg': 'Luxemburg',
  'United Kingdom': 'Großbritannien',
  'The United Kingdom Of Great Britain And Northern Ireland': 'Großbritannien',
  'The Philippines': 'Philippinen',
  'The United Arab Emirates': 'Verein. Arab. Emirate',
  'Dominican Republic': 'Dominikan. Republik',
  'Costa Rica': 'Costa Rica',
  'Puerto Rico': 'Puerto Rico',
  'Trinidad And Tobago': 'Trinidad u. Tobago',
  'Saudi Arabia': 'Saudi-Arabien',
  'Sri Lanka': 'Sri Lanka',
  'The Republic Of North Macedonia': 'Nordmazedonien',
  'The Democratic Republic Of The Congo': 'DR Kongo',
};

export function translateCountry(name) {
  return COUNTRY_NAMES[name] || name;
}
